#spring.application.name=basic

#?? ??? .properties ???? ?? ??
#.??? ????? ?? => ??? : ??? ??? ???? ??.
#server.port=8081

#?? ??? .yml ?? .yaml ???? ?? ??
#???? ??? ??? ????? ??
#server:
#   port: 8081

spring:
#  ??? jdbc? ????? jdbc?????, mybatis, jpa ? ?? ??? ??? ?.
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234